name: KLONOA.BIN
sha1: 4a94bc2176a78903405e851a4429c0901f32a06f
options:
  basename: klonoa.bin
  target_path: extract/KLONOA.BIN
  elf_path: build/klonoa.bin.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  

  ld_script_path: build/klonoa.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x800BE2F8
  

  o_as_suffix: True
  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".bss"]
  

  symbol_addrs_path:
    - config/symbol_addrs.txt
  reloc_addrs_path:
    - config/reloc_addrs.txt



  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

 
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80011800
  
    subsegments:
      - [0x800, rodata, 800]
      - [0x356C, asm, 356C] 
      - [0xA0B14, data, A0B14]
  - [0xAE000]
